# Generated by Django 4.1.3 on 2022-12-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('año_fabricacion', models.IntegerField()),
                ('cuerdas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Baterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('año_fabricacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guitarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('año_fabricacion', models.IntegerField()),
                ('cuerdas', models.IntegerField()),
            ],
        ),
    ]
